import type { Metadata } from "next";
import "./globals.css";
import MainHeader from "@/components/templates/header";

export const metadata: Metadata = {
  title: "Nestino",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <MainHeader />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}