import "./globals.css";
import MainHeader from "@/components/templates/header";
import StoreProvider from "@/redux/StoreProvider";

export const metadata = {
  title: "Nestino",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <StoreProvider>
          <MainHeader />
          <main className="flex-1">{children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}
